name: 🐞 Bug Report
description: Report something that isn't working correctly
title: "fix: <summary>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for reporting a bug!
        Please provide as much detail as possible to help us fix it.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the error here...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Steps to trigger the bug.
      placeholder: |
        1. Run command...
        2. Config file looks like...
        3. See error...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, Poetry version, etc.