name: 📚 Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "docs: <summary>"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for helping improve our documentation!
        Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is missing, unclear, or incorrect?
      placeholder: Describe the documentation issue here...
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where did you find the issue? (File, section, URL, etc)
      placeholder: e.g., README.md, Installation section, etc.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement
      description: How can we make the documentation better?
      placeholder: Suggest a fix or improvement...
    validations:
      required: false